os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.10

install:
- sudo snap install dotnet-sdk --classic
- sudo snap alias dotnet-runtime-60.dotnet dotnet
- dotnet tool install -g localappveyor

script:
- LocalAppVeyor --version
