os: linux

dist: jammy

git:
  depth: 1

language: node_js

node_js: node

cache:
  directories:
  - $HOME/.npm
  # - $HOME/.cache/pip
  # - $HOME/.cache/pipenv

install:
- npm install --global MohamedLamineAllal/foreach-cli#fix_reldir stylus

before_script:
- node --version
- npm --version
- stylus --version
- foreach --version

script:
- 'foreach --glob "output/theme/stylus/**/*.styl" --execute "stylus #{path} --out output/theme/css/#{reldir}/#{name}.css"'

after_failure:
- stylus output/theme/stylus/KiraFirstFolder/KiraFirstFile.styl --out output/theme/css/KiraFirstFolder/KiraFirstFile.css
- stylus output/theme/stylus/KiraSecondFolder/KiraSecondFile.styl --out output/theme/css/KiraSecondFolder/KiraSecondFile.css
- stylus output/theme/stylus/KiraSecondFolder/KiraSubfolder/KiraThirdFile.styl --out output/theme/css/KiraSecondFolder/KiraSubfolder/KiraThirdFile.css
- tree output
