os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.10

before_install:
- export PATH="$PATH:/home/travis/.dotnet/tools"

install:
# - wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
# - sudo dpkg -i packages-microsoft-prod.deb
# - rm packages-microsoft-prod.deb
- sudo apt-get install -y dotnet6 dotnet-runtime-6.0 apt-transport-https
- dotnet tool install -g localappveyor

script:
- LocalAppVeyor --version
