env:
  - git config --global core.quotePath false

language: python

install:
  - gem install travis

script:
  - travis lint -x

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: SashaDeploy
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: SashaSrc
  verbose: true
