os: linux

dist: jammy

git:
  depth: 1

language: node_js

node_js: node

install:
- nvm install node
- npm install --global browser-sync

cache:
  directories:
  # - node_modules
  # - $(npm config get prefix)/bin
  # - $(npm config get prefix)/lib/node_modules
  - $HOME/.npm
  - $HOME/.cache/pip
  # - $HOME/virtualenv/python3.12.0/lib/python3.12/site-packages
  # - .venv/Lib/site-packages
  # - .venv/Scripts

before_script:
- node --version
- browser-sync --version

script:
- browser-sync --logLevel debug --no-open .
# - fkill :4147 --force --verbose
