language: pytho

install:
  - gem install travis

script:
  - travis lint

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: SashaDeploy
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: SashaSrc
  verbose: true
