os: linux

dist: jammy

git:
  depth: 1

language: python

arch: arm64-graviton2

python: 3.12

install:
- pip install djlint

script:
- djlint --profile=jinja --lint KiraTemplates
- djlint --profile=jinja --lint KiraTemplates/**/*.html
