sudo: enabled
dist: xenial
language: python
python: 3.7
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1
install:
- pip install pipenv
script:
- pipenv install --dev