os: linux

dist: jammy

git:
  depth: 1

cache: false

language: python

python: 3.10

install:
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

script:
- cargo install stork-search --locked
- stork --help
