os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.12

cache:
  directories:
  # - node_modules
  # - $(npm config get prefix)/bin
  # - $(npm config get prefix)/lib/node_modules
  - $HOME/.npm
  # - $HOME/.cache/pip
  # - $HOME/.cache/pipenv
  # - .venv/Lib/site-packages
  # - .venv/Scripts

before_install:
# - ls $HOME/.cache/pipenv
# - export PIPENV_IGNORE_VIRTUALENVS=1
# - export PIPENV_SKIP_LOCK=1
# - export PIPENV_VENV_IN_PROJECT=1

install:
# - pip install pipenv
# - pipenv install --dev --verbose
- nvm install node
- npm config get cache
- npm install --global grunt-cli
- npm ci --loglevel=error

before_script:
# - ls $HOME/.cache/pipenv
# - which python
# - python --version
# - which pip
# - pip --version
# - which pipenv
- which node
- which npm
- which npx
- which grunt

script:
- node --version
- npm --version
- npx --version
- grunt --version
