os: linux

dist: jammy

git:
  depth: 1

# language: python

# python: 3.12

# arch: arm64-graviton2

cache:
- npm
- pip
# - /usr/local/lib/node_modules
# - /usr/lib/node_modules

install:
- sudo apt update
# - sudo apt install tidy
- sudo apt-get install $(grep -v "^#" snappackageslist)

script:
- tidy --version
