before_install:
- export PIPENV_IGNORE_VIRTUALENVS=1
- export PIPENV_SKIP_LOCK=1
- export PIPENV_VENV_IN_PROJECT=1

cache:
  directories:
  # - $HOME/.npm
  - $HOME/.cache/pip
  - $HOME/.cache/pipenv

dist: jammy

git:
  depth: 1

install:
- refreshenv
- pip install pipenv
- pipenv install --dev

language: python

os: linux

python: 3.13

script:
- python installation/github-release-install.py
- pipenv run fd --version
- pipenv run tidy --version
