matrix:
  include:
    - script:
      - DEPLOY=false
      - echo Sasha
      - echo Another
    - script:
      - DEPLOY=true
      - echo Sasha && echo http-server
      - echo Another

deploy:
  provider: pages
  on:
    branch: SashaMatrixDeploy
    condition:
      - script:
        - DEPLOY=true
        - echo Sasha && echo http-server
        - echo Another
  keep-history: true
  skip-cleanup: true
  target-branch: master
  local-dir: output
  repo: Kristinita/SashaTravis.github.io
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  fqdn: Kristinita.ru
  project-name: Поиск Кристиниты
  verbose: true
