os: linux

dist: jammy

git:
  depth: 1

cache: false

language: python

python: 3.10

install:
- wget https://files.stork-search.net/releases/v1.5.0/stork-ubuntu-20-04
- chmod +x stork-ubuntu-20-04

script:
- stork-ubuntu-20-04 --help
- stork --help
