os: linux

dist: jammy

git:
  depth: 1

# language: python

# python: 3.12

# arch: arm64-graviton2

cache:
- npm
- pip
# - /usr/local/lib/node_modules
# - /usr/lib/node_modules

install:
- sudo snap install tidy channel=5.6.0/stable

script:
- tidy --version
