language: python
# Python 3.7 support:
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
python: 3.6.0
# https://github.com/travis-ci/travis-yml/pull/16
sudo: true
install:
- npm install eyo -g
script:
- eyo --lint Sasha__Testing--EYo.txt