os: linux

dist: jammy

git:
  depth: 1

language: node_js

node_js: node

cache:
  directories:
  - node_modules
  - $(npm config get prefix)/bin
  - $(npm config get prefix)/lib/node_modules

install:
- sudo apt update
- sudo apt install fd-find
- sudo ln --symbolic $(which fdfind) /usr/local/bin/fd
- npm install --global @coffeelint/cli
- npm install --save-dev @coffeelint/cli

before_script:
- fd --version
- xargs --version
- coffeelint --version
- npx --version
- npx coffeelint --version
- fd -0 --extension coffee

script:
- fd -0 --extension coffee --exec coffeelint
- fd -0 --extension coffee | xargs -0 coffeelint
- fd -0 --extension coffee --exec npx coffeelint
- fd -0 --extension coffee | xargs -0 npx coffeelint
