os: linux

dist: jammy

git:
  depth: 1

language: node_js

node: node

cache:
  npm: false

install:
- npm install

script:
- env DEBUG="penthouse,penthouse:*" node KiraPenthousePassed.js
- env DEBUG="penthouse,penthouse:*" node KiraPenthouseFailed.js
