os: linux

dist: jammy

git:
  depth: 1

cache: false

language: python

python: 3.10

install:
- sudo apt install rustc

script:
- cargo install stork-search --locked
- stork --help
