os: linux

dist: jammy

git:
  depth: 1

language: node_js

node_js: node

cache:
  directories:
  - $HOME/.npm
  # - $HOME/.cache/pip
  # - $HOME/.cache/pipenv

install:
- sudo apt update
- sudo apt install fd-find
- sudo ln --symbolic $(which fdfind) /usr/local/bin/fd
- npm install --global @coffeelint/cli
- npm ci

before_script:
- fd --version
- xargs --version
- coffeelint --version
- npx --version
- npx coffeelint --version
- fd --extension coffee
- npx foreach --version

script:
- npx foreach --execute "npx coffeelint {{path}}" --glob "**/*.coffee" --ignore "node_modules/**"
- npx foreach --execute "coffeelint {{path}}" --glob "**/*.coffee" --ignore "node_modules/**"
- fd --extension coffee --exec coffeelint
- fd --extension coffee --exec npx coffeelint
- fd --print0 --extension coffee | xargs --null coffeelint
- fd --print0 --extension coffee | xargs --null npx coffeelint
