os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.12

arch: arm64-graviton2

install:
- npm install

script:
- git log -1
- "git log -1 --pretty=format:\"%s%n%n%b\" | npx commitlint --verbose"
- "git log -1 --pretty=format:\"%s%n%b\" | npx commitlint --verbose"
