os: linux

dist: jammy

git:
  depth: 1

language: python

node_js: 3.12

cache:
  directories:
  - node_modules
  - $(npm config get prefix)/bin
  - $(npm config get prefix)/lib/node_modules
  - $HOME/.cache/pip
  # - .venv/Lib/site-packages
  # - .venv/Scripts

install:
- nvm install node
- npm install --global fkill-cli http-server pa11y-ci
- pip install linkchecker

before_script:
- pa11y-ci --version
- linkchecker --version
- python -m site
- http-server --port 4147 &

script:
- pa11y-ci http://localhost:4147/KiraTestedHTML.html
- linkchecker http://localhost:4147/KiraTestedHTML.html
- fkill :4147 --force
- linkchecker http://localhost:4147/KiraTestedHTML.html
