os: linux

dist: jammy

git:
  depth: 1

# language: python

# python: 3.12

# arch: arm64-graviton2

cache:
- npm
- pip
# - /usr/local/lib/node_modules
# - /usr/lib/node_modules

install:
- sudo apt install fd-find
- npm install --global @coffeelint/cli

script:
- echo $PATH
# - export PATH="$HOME/.local/bin:$PATH"
# - echo $PATH
# - ls /usr/local/bin -d */
- ln -s /usr/bin/fdfind /usr/local/bin/fd
- alias fd=fdfind
# - whereis xargs
- whereis coffeelint
- whereis fd
- whereis fdfind
- fdfind -0 -e coffee | xargs -0 coffeelint
- fdfind -e coffee -x coffeelint
- fd -0 -e coffee | xargs -0 coffeelint
- fd -e coffee -x coffeelint
