os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.10

install:
- sudo apt-get install tidy

script:
- tidy --version
- tidy -config tidy.conf --markup no KiraExample.html
