os: linux

dist: jammy

git:
  depth: 1

language: node_js

node: node

cache:
  npm: false

install:
- npm install -g remark-cli
- npm install

script:
- remark **/*.md --silently-ignore --frail
