os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.12

cache:
  directories:
  # - $HOME/.npm
  - $HOME/.cache/pip
  # - $HOME/.cache/pipenv
  # - .venv/Lib/site-packages
  # - .venv/Scripts
  - .peru/cache

# before_install:
# - ls $HOME/.cache/pipenv
# - export PIPENV_IGNORE_VIRTUALENVS=1
# - export PIPENV_SKIP_LOCK=1
# - export PIPENV_VENV_IN_PROJECT=1

install:
- pip install peru
# - pip install pipenv
# - pipenv install --dev --verbose
# - nvm install node
# - npm config get cache
# - npm install --global grunt-cli
# - npm ci --loglevel=error

before_script:
- which python
- python --version
- which pip
- pip --version
- which peru
- peru --version
# - which node
# - which npm
# - which npx
# - which grunt

script:
- peru sync
- ls pelican-plugins
# - node --version
# - npm --version
# - npx --version
# - grunt --version
