os: linux

dist: jammy

git:
  depth: 1

cache: false

language: python

python: 3.10

install:
- sudo snap install rustup
- cargo install stork-search --locked

script:
- stork --help
