script:
- echo "Kira Goddess!"

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  target-branch: master
  local-dir: output
  repo: Kristinita/SashaTravis.github.io
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  fqdn: Kristinita.ru
  project-name: Поиск Кристиниты
  verbose: true
