os: linux

dist: jammy

git:
  depth: 1

language: node_js

node: node

cache:
  npm: false

install:
- npm install

script:
- node KiraPenthousePassed.js
- node KiraPenthouseFailed.js
