os: linux

dist: jammy

git:
  depth: 1

# language: python

# python: 3.12

arch: arm64-graviton2

cache:
- npm
- pip

install:
- sudo apt install fd-find
- npm install --global @coffeelint/cli

script:
- ln -s $(which fdfind) $HOME/.local/bin
- whereis xargs
- whereis coffeelint
- whereis fd
- fd -0 -e coffee | xargs -0 coffeelint
- fd -e coffee -x coffeelint
