git:
  depth: 1

language: python

script:
- echo "Kira Goddess!"

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: SashaDest
  github-token: 8be371f0e94d052951db0d0c401e24600cf3c2f4
  keep-history: true
  on:
    branch: KiraCustomDeployMessage
  project-name: Kristinita\\\'s Search
  verbose: true
  commit_message: bash "KiraDeploy.sh"
