dist: jammy

git:
  depth: 1

language: bash

os: linux

# cache:
#   directories:
#   - $HOME/.npm
# - $HOME/.cache/pip
# - $HOME/.cache/pipenv

install:
- sudo apt update
- sudo apt install fd-find
- sudo ln --symbolic $(which fdfind) /usr/local/bin/fd

before_script:
- fd --version
- shellcheck --version

script:
- fd --extension sh --exec echo ; --exec shellcheck
- fd --extension sh --exec echo \; --exec shellcheck
