os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.12

cache:
  directories:
  - $HOME/.npm
  - $HOME/.cache/pip
  # - $HOME/.cache/pipenv

before_install:
- export NODE_TLS_REJECT_UNAUTHORIZED=0

install:
- nvm install node
- npm install --global check-pages-cli fkill-cli http-server mkcert pa11y-ci
- pip install linkchecker

before_script:
- check-pages --version
- fkill --version
- http-server --version
- linkchecker --version
- mkcert --version
- node --version
- npm --version
- pa11y-ci --version
- pip --version
- python --version
- which node
- which npm
- which pip
- which python

script:
- mkcert create-ca
- mkcert create-cert
- >
  nohup http-server
  --cert cert.crt
  --key cert.key
  --tls &"
- check-pages https://localhost:8080/KiraTestedHTML.html
- linkchecker --config linkcheckerrc https://localhost:8080/KiraTestedHTML.html
- pa11y-ci --config .pa11y-ci.js https://localhost:8080/KiraTestedHTML.html
- fkill :8080 --force --verbose
