before_script:
- lsb_release --all
- python --version
- codespell --version

cache:
  directories:
  # - $HOME/.npm
  - $HOME/.cache/pip
  # - $HOME/.cache/pipenv

dist: noble

git:
  depth: 1

install:
- python -m pip install --upgrade pip
- pip install codespell

language: python

os: linux

python: 3.13

script:
- codespell --config codespell.cfg KiraURLs.txt
- codespell KiraURLs.txt
