after_script:
- tree output
- ls --human-readable --recursive --size output

before_script:
- node --version
- npm --version
- imagemin --version
- foreach --version
- tree output

cache:
  directories:
  - $HOME/.npm
  # - $HOME/.cache/pip
  # - $HOME/.cache/pipenv

dist: noble

git:
  depth: 1

install:
- sudo apt update
- sudo apt install tree
- npm install --global Kristinita/foreach-cli#KiraPatchReldirWindowsPaths imagemin-cli imagemin-jpegtran imagemin-optipng imagemin-webp

language: node_js

node_js: node

os: linux

script:
- 'foreach --glob "output/theme/images/**/*.{jpeg,jpg}" --execute "imagemin #{path} --plugin.jpegtran.progressive=true > output/theme/images/#{reldir}/#{name}.min#{ext}" --no-spin'
- 'foreach --glob "output/theme/images/**/*.png" --execute "imagemin #{path} --plugin.optipng.optimizationLevel=7 > output/theme/images/#{reldir}/#{name}.min#{ext}" --no-spin'
- 'foreach --glob "output/theme/images/**/*.min.{jpeg,jpg,png}" --execute "imagemin #{path} --plugin=webp > output/theme/images/#{reldir}/#{name}.webp" --no-spin'
