language: python

script:
  - cp -a SashaSrc SashaDest

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  local-dir: SashaDest
  repo: Kristinita/SashaTravis.github.io
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
  project-name: Kristinita
  verbose: true
