os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.10

before_install:
- export PATH="$PATH:/home/travis/.dotnet/tools"

install:
- sudo apt-get install -y dotnet6 dotnet-runtime-6.0
- dotnet tool install -g localappveyor

script:
- LocalAppVeyor --version
