os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.10

install:
- sudo apt-get install -y dotnet6
- dotnet tool install -g localappveyor

script:
- LocalAppVeyor --version
