os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.12

cache:
  directories:
  # - node_modules
  # - $(npm config get prefix)/bin
  # - $(npm config get prefix)/lib/node_modules
  # - $HOME/.npm
  - $HOME/.cache/pip
  - $HOME/.cache/pipenv
  # - $HOME/virtualenv/python3.12.0/lib/python3.12/site-packages
  # - .venv/Lib/site-packages
  # - .venv/Scripts

before_install:
- export PIPENV_VENV_IN_PROJECT=1
- export PIPENV_IGNORE_VIRTUALENVS=1
- export PIPENV_SKIP_LOCK=1

install:
- pip install pipenv
- pipenv install --dev --verbose

before_script:
- which python
- python --version
- which pip
- pip --version
- which pipenv

script:
- pipenv --version
