language: python

script:
  - cp -a SashaSrc SashaDest

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: SashaDest
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
  project-name: Kristinita&#39;s Search
  verbose: true
