os: linux

dist: jammy

git:
  depth: 1

language: node_js

node: node

cache:
  npm: false

before_install:
- export NPM_CHECK_INSTALLER="pnpm npm-check -y"

install:
- npm install -g pnpm
- pnpm install -D
- pnpm add npm-check -D

script:
- pnpm exec npm-check -y -i imagemin-webp
