os: linux

dist: jammy

git:
  depth: 1

language: python

python: 3.12

install:
- nvm install node
- npm install --global http-server
- pip install linkchecker

cache:
  directories:
  - node_modules
  - $(npm config get prefix)/bin
  - $(npm config get prefix)/lib/node_modules
  - $HOME/.cache/pip
  # - $HOME/virtualenv/python3.12.0/lib/python3.12/site-packages
  # - .venv/Lib/site-packages
  # - .venv/Scripts

before_script:
- linkchecker --version
- http-server --version

script:
- http-server --port 4147 &
- linkchecker --config linkcheckerrc http://localhost:4147/KiraNonValidCSS.html
# - fkill :4147 --force --verbose
