language: node_js

node_js:
  - 'node'

stages:
  - compile
  - test

install:
  - npm install -g markdownlint-cli

jobs:
  include:
    - stage: compile
      script: mv SashaMarkdownlint.md SashaNewMarkdownlint.md
      script: mv SashaMarkdownlint.md SashaNewMarkdownlint2.md
    - stage: test
      script: markdownlint SashaNewMarkdownlint2.md
