os: linux

dist: jammy

git:
  depth: 1

# language: python

# python: 3.12

# arch: arm64-graviton2

cache:
- npm
- pip
# - /usr/local/lib/node_modules
# - /usr/lib/node_modules

addons:
  apt:
    packages:
    - parallel

install:
- bash travis-install.sh
# - sudo apt update
# - sudo apt install tidy
# - sudo apt-get install $(egrep -v "^(#|$)" snappackageslist)

script:
- fd --version
- tidy --version
