init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - set PYTHONIOENCODING=utf-8

environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

install:
  - cinst nodejs -y
  - npm install --save-dev @commitlint/travis-cli

test_script:
  - commitlint-travis