platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:

  PYTHON: C:\Python312-x64

install:
- pip install djlint

test_script:
- djlint --profile=jinja --lint KiraTemplates
- djlint --profile=jinja --lint KiraTemplates/**/*.html
