platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
# - "%PYTHON%\\Lib\\site-packages"
# - "%PYTHON%\\Scripts"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Lib\\site-packages"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Scripts"

install:
- choco install nodejs --yes
- npm install --global browser-sync

before_build:
- node --version
- browser-sync --version

build_script:
- browser-sync --logLevel debug --no-open .
