clone_depth: 1

# environment:
#   APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

platform: x64

# cache:
# - "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

install:
- choco install --yes fd shellcheck

before_build:
- fd --version
- shellcheck --version

build_script:
- fd --extension sh --exec echo ; --exec shellcheck

on_failure:
- fd --extension sh --exec echo \; --exec shellcheck
