build_script:
- gh-release-install Kristinita/tidy-html5 tidy.exe KiraNonexistentDirectory/KiraNonexistentSubdirectory --verbose

cache:
# - "%LOCALAPPDATA%\\npm-cache"
- "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

install:
- pip install gh-release-install

platform: x64
