clone_depth: 1

environment:
  APPVEYOR_API_KEY:
    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

install:
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10

build_script:
- localappveyor lint --token %APPVEYOR_API_KEY%
