platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  PYTHON: C:\Python310-x64

init:
- SETX PYTHONIOENCODING utf-8
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
- ps: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
- scoop install rustup

build_script:
- cargo install stork-search --locked
- stork --help
