platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  nodejs_version: "21"

cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules"
- "%APPVEYOR_BUILD_FOLDER%/node_modules"

install:
- ps: Install-Product node $env:nodejs_version
- choco install fd --yes
- npm install --global @coffeelint/cli
- npm install --save-dev @coffeelint/cli

before_build:
- where npx
- where xargs
- fd --version
- xargs --version
- node --version
- npx --version
- coffeelint --version
- npx coffeelint --version
- fd --extension coffee

build_script:
- fd --extension coffee --exec coffeelint

on_failure:
- fd --print0 --extension coffee | xargs --null coffeelint
- fd --print0 --extension coffee | xargs --null npx coffeelint
- fd --extension coffee --exec npx coffeelint
