platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  nodejs_version: "21"

cache:
- "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

install:
- ps: Install-Product node $env:nodejs_version
- choco install --yes fd
- npm install --global @coffeelint/cli
- npm ci

before_build:
- where npx
- where xargs
- fd --version
- xargs --version
- node --version
- npx --version
- coffeelint --version
- npx coffeelint --version
- fd --extension coffee
- npx foreach --version

build_script:
- npx foreach --execute "npx coffeelint {{path}}" --glob "**/*.coffee" --ignore "node_modules/**"
- npx foreach --execute "coffeelint {{path}}" --glob "**/*.coffee" --ignore "node_modules/**"
- fd --extension coffee --exec coffeelint

on_failure:
- fd --print0 --extension coffee | xargs --null coffeelint
- fd --print0 --extension coffee | xargs --null npx coffeelint
- fd --extension coffee --exec npx coffeelint
