before_build:
- node --version
- npm --version
- imagemin --version
- foreach --version

build_script:
- 'foreach --glob "output/theme/images/**/*.{jpg,png}" --execute "imagemin #{path} --plugin=webp > output/theme/images/#{reldir}/#{name}.webp"'
- tree output /a /f

cache:
- "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

install:
- choco install --yes nodejs
- npm install --global Kristinita/foreach-cli#KiraPatchReldirWindowsPaths imagemin-cli imagemin-webp

platform: x64
