platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:

  PYTHON: C:\Python312-x64

install:
- npm install

# [INFO] Try with private e-mail. Test:
# https://stackoverflow.com/a/71542189/5951529
build_script:
script:
- git log -1
- "git log -1 --pretty=format:\"%s%n%n%b\" | npx commitlint --verbose"
- "git log -1 --pretty=format:\"%s%n%n%b\" | npx commitlint --verbose"
