init:
- setx PIPENV_VENV_IN_PROJECT 1
- refreshenv
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- set PYTHONIOENCODING=utf-8

environment:
  matrix:
  - PYTHON: C:\Python37-x64
    PYTHON_VERSION: 3.7
    PYTHON_ARCH: 64

install:
- pip install pipenv

build_script:
- pipenv install --dev