clone_depth: 1

# environment:
#   APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

platform: x64

# cache:
# - "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

install:
- choco install --yes chocolatey.config

before_build:
- fd --version
- tidy --version

build_script:
- fd --extension html --exec tidy -config tidy.conf --markup no

on_failure:
- fd --extension html --exec tidy -config tidy.conf -modify --show-errors 0 --show-warnings 0 || true
- fd --extension html --exec tidy -config tidy.conf --markup no
