platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:

  PYTHON: C:\Python312-x64

install:
- npm install

build_script:
- git log -1 --pretty=format:"%s" | npx commitlint --verbose
