############
# AppVeyor #
############
# AppVeyor continuous integration
# Comments:
# https://github.com/Kristinita/KristinitaPelican/blob/master/appveyor.yml
init:
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- set PYTHONIOENCODING=utf-8

platform: x64

environment:
  matrix:
  - PYTHON: C:\Python36-x64
    PYTHON_VERSION: 3.6.5
    PYTHON_ARCH: 64

install:
- python -m pip install --upgrade pip
- pip install erichek

build_script:
- erichek