# Use CircleCI 2.0
# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/configuration-reference/
version: 2

jobs:
  build:
    steps:
    - run:
      command: |
        pip install flake8 pydocstyle pyfancy pyroma vulture
    - run:
      command: |
        flake8 .
        pydocstyle
        pyroma .
        vulture .

# machine:
#   python:
#     # [WARNING] No higher Python versions at May 2018 in Circle CI
#     version: 3.7.0

# dependencies:

#   # [DONE]
#   # # [FIXME]: temporary solution, until pyfancy bug not fix
#   # # https://stackoverflow.com/a/37375913/5951529
#   # # https://github.com/ilovecode1/Pyfancy-2/issues/31#issuecomment-362977812
#   # override:
#   #   - echo "Not install dependencies from requirements.txt"

#   post:
#     - pip install flake8
#     - pip install pydocstyle
#     - pip install pyfancy
#     - pip install pyroma
#     - pip install -U setuptools
#     - pip install vulture

# test:
#   override:
#     - flake8 .
#     - pydocstyle
#     - pyroma .
#     - vulture .
